---
stages:
  - lint
  - test
  - doc

cache:
  paths:
    - vendor/

before_script:
  - bundle config set path 'vendor'

.tests:
  before_script:
    - apt-get update -qy
    - apt-get install -y libapt-pkg-dev
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script: rake test
  stage: test

test:2.3:
  extends: .tests
  image: 'ruby:2.3'
  script:
    - bundle exec rake

test:2.4:
  extends: .tests
  image: 'ruby:2.4'
  script:
    - bundle exec rake

test:2.5:
  extends: .tests
  image: 'ruby:2.5'
  script:
    - bundle exec rake

test:2.6:
  extends: .tests
  image: 'ruby:2.6'
  script:
    - bundle exec rake

test:2.7:
  extends: .tests
  image: 'ruby:2.7'
  script:
    - bundle exec rake

lint:
  image: 'ruby:2.7-slim'
  before_script:
    - apt-get update -qy
    - apt-get install -y libapt-pkg-dev cppcheck
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script:
    - bundle exec rake cppcheck
  stage: lint

pages:
  image: 'ruby:2.7-slim'
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script:
    - bundle exec rake rdoc
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  stage: doc
