---
before_script:
  - apt-get update -qy
  - apt-get install -y libapt-pkg-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

test:
  script:
    - bundle exec rake
