---
stages:
  - lint
  - test
  - doc

cache:
  paths:
    - vendor/

before_script:
  - bundle config set path 'vendor'

.tests:
  before_script:
    - apt-get update -qy
    - apt-get install -y libapt-pkg-dev
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script: bundle exec rake
  stage: test

test:3.0:
  extends: .tests
  image: 'ruby:3.0'

test:3.1:
  extends: .tests
  image: 'ruby:3.1'

test:3.2:
  extends: .tests
  image: 'ruby:3.2'

lint:
  image: 'ruby:3.2-slim'
  before_script:
    - apt-get update -qy
    - apt-get install -y libapt-pkg-dev cppcheck
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script:
    - bundle exec rake cppcheck
  stage: lint

audit:
  image: 'ruby:3.2-slim'
  before_script:
    - apt-get update -qy
    - apt-get install -y git
    - gem install bundler bundler-audit --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  allow_failure: true
  script:
    - bundle-audit update
    - bundle-audit check
  stage: lint

pages:
  image: 'ruby:3.2-slim'
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs "$(nproc)" "${FLAGS[@]}"
  script:
    - bundle exec rake rdoc
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  stage: doc
