sudo: required
dist: trusty

language: ruby
bundler_args: --jobs=3 --retry=3
cache: bundler
before_install:
  - sudo apt update
  - sudo apt install -y libapt-pkg-dev
  - gem install --remote bundler
rvm:
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
