---
dist: bionic
sudo: true
language: ruby
cache: bundler
before_install:
  - sudo apt install -y libapt-pkg-dev
  - gem install --remote bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email: false
script:
  - bundle exec rake
