sudo: required
dist: trusty

language: ruby
cache: bundler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libapt-pkg-dev ruby-dev
rvm:
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
