sudo: required
dist: trusty

language: ruby
cache: bundler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libapt-pkg-dev ruby-dev
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-head
