sudo: required
dist: trusty

language: ruby
bundler_args: --jobs=3 --retry=3
before_install:
  - gem update --remote bundler
cache: bundler
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libapt-pkg-dev
rvm:
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
